# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-05-09 10:46:13 -0400 by agoldfarb:
gem "jekyll", "~> 3.8"
